### ISSUE TITLE
Error compilation

### ISSUE THREAD

**Issue by Nivekiba** [chestnut-sandbox/Chestnut#2]
The version patched of llvm didn't compile well:

I got this error:

![image](https://user-images.githubusercontent.com/20845649/148839546-f63f5834-d276-4e91-b4cb-dc91c9adaff0.png)

**Comment by Nivekiba** [comment]
Also, can I have the "sandboxing.o" file mentioned in the patch ? for now, when I compiled specifying the good linker, I missed the sandboxing.o file

**Comment by cc0x1f** [comment]
> The version patched of llvm didn't compile well:
> 
> I got this error:
> 
> ![image](https://user-images.githubusercontent.com/20845649/148839546-f63f5834-d276-4e91-b4cb-dc91c9adaff0.png)

There was an error in the patch and I fixed. Was some remnant from an earlier version

**Comment by cc0x1f** [comment]
> Also, can I have the "sandboxing.o" file mentioned in the patch ? for now, when I compiled specifying the good linker, I missed the sandboxing.o file

sandboxing.o should be chestnut.o and is provided in the libchestnut folder. Error during the cleanup process. The new patch now includes the correct name.
